# Generated by Django 3.0.2 on 2020-01-17 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('postnom', models.CharField(max_length=255)),
                ('prenom', models.CharField(max_length=255)),
                ('lieu_naissance', models.CharField(max_length=255)),
                ('date_naissance', models.DateField()),
                ('sexe', models.CharField(choices=[('F', 'F')], max_length=1)),
                ('Etat_civil', models.CharField(choices=[('C', 'CELIBATAIRE'), ('M', 'MARIE'), ('D', 'DIVORCE'), ('V', 'VEUF')], max_length=1)),
                ('email', models.EmailField(max_length=254)),
                ('adresse', models.CharField(max_length=255)),
                ('nom_pere', models.CharField(max_length=255)),
                ('nom_mere', models.CharField(max_length=255)),
                ('diplome_pourcent', models.IntegerField()),
                ('diplome_option', models.CharField(max_length=255)),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['registration_date'],
            },
        ),
    ]
