# Generated by Django 3.0.2 on 2020-01-19 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='departement',
            field=models.CharField(choices=[('I', 'INFORMATIQUE'), ('M', 'MECANIQUE'), ('N', 'MINES'), ('C', 'CONSTRUCTION')], default='I', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='faculte',
            field=models.CharField(choices=[('S', 'SCIENCES APPLIQUEES'), ('M', 'MEDECINE'), ('E', 'ECONOMIE'), ('D', 'DROIT')], default='S', max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='adresse',
            field=models.CharField(max_length=155),
        ),
        migrations.AlterField(
            model_name='student',
            name='diplome_option',
            field=models.CharField(max_length=55),
        ),
        migrations.AlterField(
            model_name='student',
            name='lieu_naissance',
            field=models.CharField(max_length=55),
        ),
        migrations.AlterField(
            model_name='student',
            name='nom',
            field=models.CharField(max_length=55),
        ),
        migrations.AlterField(
            model_name='student',
            name='nom_mere',
            field=models.CharField(max_length=55),
        ),
        migrations.AlterField(
            model_name='student',
            name='nom_pere',
            field=models.CharField(max_length=55),
        ),
        migrations.AlterField(
            model_name='student',
            name='postnom',
            field=models.CharField(max_length=55),
        ),
        migrations.AlterField(
            model_name='student',
            name='prenom',
            field=models.CharField(max_length=55),
        ),
        migrations.AlterField(
            model_name='student',
            name='sexe',
            field=models.CharField(choices=[('M', 'Masculin'), ('F', 'Feminin')], max_length=1),
        ),
    ]
