# Generated by Django 3.0.2 on 2020-01-19 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20200119_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='annee_academique',
            field=models.CharField(default='2019-2020', max_length=55),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='promotion',
            field=models.CharField(choices=[('1', 'G1'), ('2', 'G2'), ('3', 'G3'), ('4', 'L1'), ('5', 'L2')], default='1', max_length=1),
            preserve_default=False,
        ),
    ]
